version: '3.8'
services:
  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: ./backend
    ports: ["3001:3001"]
    depends_on: [mongodb, redis]
    environment:
      MONGODB_URI: mongodb://mongodb:27017/taskqueue
      REDIS_URL: redis://redis:6379

  worker:
    build: ./backend
    command: node src/worker.js
    deploy:
      replicas: 3 # Run 3 workers in parallel!
    depends_on: [mongodb, redis]
    environment:
      MONGODB_URI: mongodb://mongodb:27017/taskqueue
      REDIS_URL: redis://redis:6379

volumes:
  mongo_data: